### ISSUE TITLE
Installation using npm install creates binary output in terminal ...

### ISSUE THREAD

**Issue by McMornan** [Tom-Hirschberger/MMM-Serial-Notifications#3]
Hi,

I did a fresh pull from MagicMirror (2.18), installed it (npm install). I then pulled this module and called npm install in the modules directory... when the magicmirror rebuild command is issued during postinstall I get loads of binary output which does not end ... any idea what I did wrong ?

(atm I let it run and pipe the output into nirvana, to see if it ever ends ... 'npm install > /dev/null 2>%1')

Thanks,
Lars

**Comment by Tom-Hirschberger** [comment]
Hi and sorry for the late answer... Do not know why I did not see the issue.

Can you provide some more information....
Which hardware do you use?
Which Operating System? Raspberry OS Buster or Bullseye?
Can you provide a snippet of the output?

**Comment by Tom-Hirschberger** [comment]
Hi, I did some fresh installs on 32bit and 64bit in the last days and did not have any problems. As you never provided more information I will close the issue.
Feel free to reopen it if the problem still exists.
