### ISSUE TITLE
Request (not an issue)

### ISSUE THREAD

**Issue by Clintvd** [Tom-Hirschberger/MMM-Serial-Notifications#5]
Hi Tom,

Back again with a question. 
What would the configuration look like for showing the temperature from a dht11 temp/humidity sensor.

Thank you in advance.

**Comment by Tom-Hirschberger** [comment]
Hi,

are you sure that your sensor sends the data via a serial interface or is it connected to the pi directly?

If it is connected directly you can use my MMM-CommandToNotification to read the data of your sensor. The module includes a example script for DHT11 already.

**Comment by Tom-Hirschberger** [comment]
You will need a module like MMM-ValuesByNotification to display the data as both MMM-Serial-Notifications and MMM-CommandToNotification only send notifications.

**Comment by Tom-Hirschberger** [comment]
Hi, do you need more help or can I close the issue?

**Comment by Clintvd** [comment]
Hi @Tom-Hirschberger , sorry for the late reply. You can close the issue!

**Comment by Tom-Hirschberger** [comment]
No problem, your welcome
